/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Db.db;
import dao.QuestionPaperDaoimpl;
import dao.UserDaoImpl;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Question;
import model.Teacher;
import model.User;


/**
 *
 * @author Mingmar Hyolmo
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form addUser
     */
    public AddUser() {
        initComponents();
        this.setTitle("Add User");
        Toolkit toolkit= getToolkit();
        Dimension size= toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonSaveForm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        departCmb = new javax.swing.JComboBox();
        username = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        confirmTxt = new javax.swing.JPasswordField();
        passwordTxt = new javax.swing.JPasswordField();
        subjectTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(41, 144, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Confirm  *");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 120, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 200, -1));

        jButtonSaveForm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSaveForm.setText("Save Form");
        jButtonSaveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFormActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSaveForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 200, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_50px.png"))); // NOI18N
        jLabel1.setText("Add User");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 20, 280, 60));

        jLabel4.setText("Department *");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 192, -1));

        departCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        departCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departCmbActionPerformed(evt);
            }
        });
        jPanel2.add(departCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 198, -1));

        username.setText("User Name *");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 374, 200, 20));

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 200, -1));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, -1));

        jLabel8.setText("Name *");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, -1));

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 490, -1));

        jLabel24.setText("Email *");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 210, -1));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 208, -1));

        jLabel25.setText("Password *");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 120, -1));
        jPanel2.add(confirmTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 210, -1));
        jPanel2.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 210, -1));

        subjectTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTxtActionPerformed(evt);
            }
        });
        jPanel2.add(subjectTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, -1));

        jLabel6.setText("Subject *");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 200, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AdminLogin ad= new AdminLogin();
        ad.setVisible(true);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void departCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departCmbActionPerformed
        // TODO add your handling code here:
        
         //departCmb.removeAllItems();
            Connection con = null;
            con = db.getdbcon();
            Statement stmt = null;

            try {
                stmt = con.createStatement();
                //String department = (String)departCmb.getSelectedItem();
                String sql = "select department_name from department";
                //where department_name = '" +department +"'";
                ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String dept = rs.getString("department_name");
                    departCmb.addItem(dept);
                }

        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_departCmbActionPerformed

    private void jButtonSaveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFormActionPerformed
        // TODO add your handling code here:
        Teacher t = new Teacher();

        String depart= departCmb.getSelectedItem().toString();
        String name=nameTxt.toString();
        String subject=subjectTxt.toString();         
        String email=emailtxt.toString();
        String username=userNameTxt.toString();
        String password=passwordTxt.toString();
        String confirm=confirmTxt.toString();

        if (depart.isEmpty() || name.isEmpty()|| subject.isEmpty() ||email.isEmpty() || username.isEmpty() ||password.isEmpty() ||confirm.isEmpty()){
            JOptionPane.showMessageDialog(null,"no field should be empty!!!");
        }else{

            t.setDepartment(depart);
            t.setName(name);
            t.setSubject(subject);
            t.setEmail(email);
            t.setUserName(username);
            t.setPassword(password);
            t.setConfirm(confirm);

            UserDaoImpl udao = new UserDaoImpl();
            if(udao.addTeacher(t)){

                JOptionPane.showMessageDialog(null,"User Added added Successfully!!!");

            }else{
                JOptionPane.showMessageDialog(null, "Failed !!!");
            }
        }
        
//        int a= JOptionPane.showConfirmDialog(jButtonSaveForm, "Are you sure?");
//        if(a==JOptionPane.YES_OPTION){
//            dispose();
//            ShowUser us= new ShowUser();
//            us.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            us.setVisible(true);
//            this.dispose();
//        }

    }//GEN-LAST:event_jButtonSaveFormActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        departCmb.setSelectedIndex(0);
        userNameTxt.setText("");
        nameTxt.setText("");
        subjectTxt.setText("");
        emailtxt.setText("");
        passwordTxt.setText("");
        confirmTxt.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void subjectTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmTxt;
    private javax.swing.JComboBox departCmb;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSaveForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField subjectTxt;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
